spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/question-paper
    username: postgres
    password: root
#    hikari:
#      schema : admin

spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: update
  show-sql: true

server:
  port: 8081


  spring:
    cache:
      type: redis
    redis:
      host: 127.0.0.1
      port: 6379